name: Website Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-region: us-west-2
      - run: aws s3 sync ./website s3://coltonnewellresume
      - run: aws cloudfront create-invalidation
            --distribution-id E10S2E9ZOYB1U2
            --paths "/*"
